plugins { id 'com.android.application' }
android {
    namespace 'it.edo.codecprobe'
    compileSdk 35
    defaultConfig {
        applicationId 'it.edo.codecprobe'
        minSdk 29
        targetSdk 35
        versionCode 2
        versionName '0.2'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
